image: node:10

cache:
  paths:
    - node_modules/

stages:
  - setup
  - deploy

setup:
  stage: setup
  script: npm install now

deploy-staging:
  stage: deploy
  script:
    - yarn ci:deploy:staging
  only:
    - staging
    - merge_requests

deploy-production:
  stage: deploy
  script:
    - yarn ci:deploy:prod
  only:
    - master
    - merge_requests
