image: node:10

cache:
  paths:
    - node_modules/

stages:
  - setup
  - deploy

setup:
  stage: setup
  script: npm install now

deploy-staging:
  stage: deploy
  script:
    - npm run ci:deploy:staging
  only:
    - staging

deploy-production:
  stage: deploy
  script:
    - npm run ci:deploy:prod
  only:
    - master
